In [1]:
import pandas as pd
import sys
from logic_files.data_loader import load_qs_data, prepare_baseline
from logic_files.simulator import simulate_scenario, metric_cols
from typing import Dict

In [2]:
# Load and prepare data
data, weights = load_qs_data()
baseline = prepare_baseline(data)

# Define a test scenario for UEA
new_scores = {
    'Academic Reputation': 72.5,
    'Citations per Faculty': 70.0,
    'Employer Reputation': 60.0,
    'Employment Outcomes': 55.0,
    'Faculty Student Ratio': 55.0,
    'International Faculty Ratio': 65.0,
    'International Research Network': 66.0,
    'International Student Ratio': 68.0,
    'Sustainability': 50.0,
    'International Student Diversity': 75.0
}


# Run simulation
updated_df, result = simulate_scenario(baseline, weights, 'The University of East Anglia', new_scores)

#print(result)
updated_df.head(10)

,institution,total_score,Academic Reputation,Citations per Faculty,Employer Reputation,Employment Outcomes,Faculty Student Ratio,International Faculty Ratio,International Research Network,International Student Diversity,International Student Ratio,Overall,Sustainability,rank,Weighted_Score
558,Massachusetts Institute of Technology (MIT),100.0,100.0,100.0,100.0,100.0,100.0,100.0,94.1,92.3,91.6,100.0,93.8,1,98.975
12,"Imperial College of Science, Technology and Me...",99.4,99.6,95.0,100.0,95.9,99.3,100.0,97.5,100.0,100.0,99.4,98.3,2,98.395
546,Stanford University,98.9,100.0,99.7,100.0,100.0,100.0,94.2,96.5,76.1,73.5,98.9,95.4,3,97.920
43,The University of Oxford,97.9,100.0,91.0,100.0,100.0,100.0,98.8,100.0,98.7,98.6,97.9,77.9,4,96.965
599,Harvard University,97.7,100.0,100.0,100.0,100.0,98.3,79.1,99.4,60.6,81.4,97.7,77.8,5,96.715
534,The University of Cambridge,97.2,100.0,88.6,100.0,100.0,100.0,100.0,99.2,93.6,93.1,97.2,78.4,6,96.255
330,ETH Zurich (Swiss Federal Institute of Technol...,96.7,99.7,98.8,96.3,95.0,71.7,100.0,95.8,73.9,99.3,96.7,99.6,7,95.770
481,National University of Singapore (NUS),95.9,99.9,95.9,98.2,100.0,71.5,100.0,92.4,72.1,96.9,95.9,90.0,8,94.995
636,University College London,95.8,99.9,80.9,99.4,89.3,94.8,99.6,99.9,100.0,100.0,95.8,98.5,9,94.905
31,California Institute of Technology (Caltech),94.3,98.3,100.0,99.2,49.1,100.0,100.0,61.8,91.4,90.7,94.3,79.2,10,93.410

In [3]:
updated_df[updated_df['institution']=='The University of East Anglia']

,institution,total_score,Academic Reputation,Citations per Faculty,Employer Reputation,Employment Outcomes,Faculty Student Ratio,International Faculty Ratio,International Research Network,International Student Diversity,International Student Ratio,Overall,Sustainability,rank,Weighted_Score
278,The University of East Anglia,39.4,72.5,70.0,60.0,55.0,55.0,65.0,66.0,75.0,68.0,39.4,50.0,125,65.45