In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/qs_data.csv', encoding='latin1')

In [3]:
df

,year,institution,rank,score,metric
0,2023,Universidad del Valle,501.0,16.9,Employer Reputation
1,2023,Beijing Jiaotong University,601.0,11.8,International Student Ratio
2,2024,Free University of Bozen-Bolzano,601.0,5,Academic Reputation
3,2026,Ohio State University,131.0,71.1,Academic Reputation
4,2025,Hokkaido University,613.0,18.7,International Faculty Ratio
...,...,...,...,...,...
81692,2025,"Universita' degli Studi ""G. d'Annunzio"" Chieti...",701.0,3.3,Faculty Student Ratio
81693,2023,Western Michigan University,501.0,6.6,Employer Reputation
81694,2027,University of Toledo,801.0,15.8,Employment Outcomes
81695,2024,Canterbury Christ Church University,701.0,5.8,Faculty Student Ratio
81696,2027,Western University,24.0,95.3,Sustainability

In [4]:
df["metric"] = df["metric"].replace({
    "International Students": "International Student Ratio",
    "International Faculty": "International Faculty Ratio",
})

In [5]:
df.head()

,year,institution,rank,score,metric
0,2023,Universidad del Valle,501.0,16.9,Employer Reputation
1,2023,Beijing Jiaotong University,601.0,11.8,International Student Ratio
2,2024,Free University of Bozen-Bolzano,601.0,5,Academic Reputation
3,2026,Ohio State University,131.0,71.1,Academic Reputation
4,2025,Hokkaido University,613.0,18.7,International Faculty Ratio

In [7]:
df["score"] = (
    pd.to_numeric(
        df["score"].replace("-", pd.NA),
        errors="coerce"
    )
)

In [8]:
df['score'].unique()

array([ 16.9,  11.8,   5. ,  71.1,  18.7,   4. ,   6.5,  99.9,   2.1,
        33. ,   1.6,   1.4,  61.2,  36.6,   nan,   1.1,   2.7,  18.8,
        80.6,  11.7,   9.2,  98.7,  66.5,  10.5,  22.7,  80.2,  55.1,
         3. ,   7.8,   4.3,  22.8,   1.5,   1.2,  37.9,  23.5,   1.8,
        22.3,  10. ,  35.5,  23.4,  33.7,  18.1,   1. ,   5.5,  74.6,
        45.6,   8.5,  33.3,  29. ,   5.9,  31.4,  12.2,   3.9,   5.1,
         3.5,  13.8,   2.8,   8. ,   8.2,  16.2,   1.3,   6.4,  93.4,
        57.6,   3.4,  95.8,  23.3,  34.9,   4.9,  38.8,  12. ,  19.1,
        18. ,   7.6,  63.2,  17.9,  48.8,  10.4,  78.6,  32.7,  11.2,
        53.3,   2.6,  14.3,  16.7,   9.8,  79.5,  13.7,  77.8,  28.7,
        15.3,  46.3,   9.6,  80.5,  44.8,  43.2,  86.3,  64.6,  11.5,
        17.3,  79.6,  83.4,  51.6,  82.5,   5.7,  28.2,   6.8,  53.8,
         9.1,   4.8,  33.8,  76. ,  49.6,  34. ,   9.7,  99.6,   2.9,
        66.1,  75.2,  43.3,  27.8, 100. ,  91.6,   2.5,   7.3,   4.2,
        51.9,  10.1,  12.9,  11.6,  10.9,  43.5,  66.4,   7.7,   9. ,
        42.6,  56.6,  59.5,  14.4,  26.1,  44.2,  96.3,  29.4,   4.4,
         8.9,   9.4,  29.2,  25.4,  85.2,  44.9,  32.8,  58.8,  51.8,
        24.6,   5.3,  51.4,   8.3,  62.2,  74. ,  20.7,  28.5,   9.3,
         3.6,  16.4,  14.9,  22.4,  87.2,  19.3,  73.4,  18.2,  28.4,
        94.4,   4.7,  11.3,  34.8,  94.6,  25.7,  12.3,  47.6,   2. ,
        89.8,   6.6,  49.9,  96.8,  88.5,   1.9,  39.4,  29.3,  50.2,
         6.1,  23.2,  12.4,  15.1,  66.8,  80.3,  57. ,   3.8,  68.4,
        11. ,  96.6,  68.5,  27.3,  74.4,  12.6,   4.6,  48.4,  27.4,
        24. ,  13.5,   7.5,  12.8,  92.7,   6.2,  16.1,  99. ,  32. ,
        96.7,  84.3,  41.7,   7.4,  35.1,  97.9,  43.1,   5.4,  15.9,
         5.8,  63.5,  14.2,  61.8,  38.1,  51.1,  17.8,  52.1,  62.5,
        46.9,  72.8,  60. ,   6.7,  40.2,  75.1,  47.8,  65.8,  47.7,
        41.1,  76.6,   2.3,   5.2,  71.5,  20.8,   6. ,  16.5,  13.4,
        94. ,  26.9,  46. ,  34.5,   8.7,  92.3,  19.2,  29.6,  10.3,
        99.8,  12.5,  14.1,  51.2,  25.6,  83.6,  56.9,  26. ,  94.9,
        21.5,  92.5,  38.7,  81.2,  13. ,   1.7,  95. ,  39.8,  43.8,
         2.2,  52.5,   3.1,  60.3,  90.5,  78.3,  12.1,  27.1,  15.7,
        97.8,  74.7,   3.2,  34.2,  24.1,  98.6,  30.2,  62.6,   4.5,
        62.7,  94.1,  18.9,  52.8,  44.5,  32.1,  35.8,  83.8,   3.3,
        19.6,  38.5,  52.3,  46.2,  70.3,  34.7,  37.6,  20.1,  12.7,
        25.9,  57.7,  42.7,  93. ,  10.6,  10.7,  89.2,  77.7,   3.7,
        21.3,  77.6,  87.3,  90. ,  73.9,  90.7,  19. ,   2.4,  14.5,
        10.2,  88.6,  36.2,  77.9,  97.5,  97.1,  15.2,  96.9,  43.6,
        42.1,  35.6,  16. ,  42.2,  48. ,   7.9,   7.2,  44.1,  49.1,
        11.4,   9.9,  43.7,  27. ,  89.6,  25.1,  40.3,  26.7,  52. ,
        24.9,  33.2,  97. ,  39.6,  30.4,  20.5,  59.7,  22. ,   7.1,
        54.8,  25.5,  42. ,  46.4,  32.5,  16.3,  84.2,  71.9,  28.8,
        21.9,  30.5,  14. ,  93.5,  51.3,  95.5,  98.9,  28.3,  33.1,
        13.2,  86.6,  67.3,  29.1,  50.6,  19.4,  51. ,  33.5,  31.7,
        18.3,  37.5,   6.3,  46.6,   5.6,  19.8,  22.5,  69.6,  89.7,
        27.7,  25.2,  68.7,  30.1,   8.1,  55.6,  98.3,  31.3,  65.5,
        24.8,  39.5,   4.1,  45.1,  17.1,  11.1,  61.6,  24.4,  55.5,
        52.7,  81.3,  83.2,  78.7,  22.2,  30.3,  29.5,  13.6,  15.6,
        93.1,  18.6,  30.8,  82. ,  65.4,   8.6,  16.8,  96.1,  81.4,
        85.3,  37.2,  58.9,  14.8,  13.9,  26.3,  43. ,  91.3,  85.1,
        97.2,  60.6,  27.6,  37.3,  60.7,  56.7,  49.7,  92. ,  39.9,
        34.4,  65.7,  97.3,  50. ,  54.6,  54.5,  27.5,  41.4,  19.5,
        37.4,  44.4,  54.3,  87.4,  50.9,  60.2,  38.2,  31.6,  69.3,
        47.4,  46.1,  73.6,  21.2,  83.3,  91.9,  81.7,  84.5,  31. ,
        94.5,  17.7,  84.4,  49.8,  89.4,  38.6,  53.2,  94.8,  27.2,
        35. ,  23.6,  38.3,  59. ,  32.2,  53.5,  18.5,  22.6,   7. ,
        14.7,  36.7,  45.7,  89. ,  56.3,  13.1,  68.8,  72.4,  84.9,
        32.3,  38.4,  98.1,  95.4,  15.5,  83.1,  24.7,  69. ,  19.7,
        63.1,  23.1,  17.2,  71. ,  92.2,  15.4,  13.3,  64.7,  45.9,
        15. ,  70.9,  31.2,  21.1,  81.6,  28.9,  23.9,  49.5,  37. ,
        47. ,  88.2,  15.8,  88.3,  91.5,  72.9,   8.8,  49. ,  99.1,
        20.6,  70. ,  36.4,  86.9,  78.8,  83.5,  50.5,  56. ,  53.7,
        66.3,  72.1,  69.7,  31.8,  73.8,  70.4,  39.3,  47.2,  69.9,
        20.3,  64. ,  99.3,  23.7,  48.3,  25. ,  42.9,  26.6,   8.4,
        76.4,  89.9,  71.6,  76.3,  26.4,  99.7,  44.7,  68.6,  61.3,
        54.2,  40.6,  11.9,  41.8,  83.9,  30.6,   6.9,  41.6,  54.1,
        97.4,  27.9,  34.1,  66. ,  32.4,  58.2,  35.3,  36. ,  61.4,
        80. ,  66.7,  98.2,  57.9,  14.6,  67.7,  90.2,  20.9,  44.6,
        55.9,  55.7,  41.2,  47.1,  79. ,  21.7,  79.9,  66.2,  92.1,
        71.2,  36.9,  72.7,  36.8,  73.2,  99.4,  33.6,  46.7,  58.1,
        33.9,  66.9,  22.9,  64.1,  96. ,  48.9,  63.3,  65.9,  37.1,
        98.4,  81.9,  42.8,  45.2,  29.9,  67.2,  21. ,  24.3,  79.7,
        39.2,  40.5,  71.3,  91.4,  75.3,  45.3,  17.5,  53.1,  17.6,
        72.3,  25.8,  99.5,  90.1,  82.7,  10.8,  59.2,  94.2,  57.2,
        91.2,  48.6,  40.7,  62.4,  43.4,  51.7,  23. ,  28. ,  38. ,
        90.6,  40. ,  91.7,  26.2,  59.6,  83.7,  68. ,  55.2,  21.8,
        50.1,  32.6,  85.7,  84. ,  23.8,  61. ,  92.6,  60.8,  76.7,
        84.1,  87.9,  66.6,  17. ,  22.1,   9.5,  28.6,  86.2,  36.1,
        86.4,  97.7,  26.5,  95.7,  36.3,  61.7,  70.1,  35.4,  24.2,
        30.9,  29.7,  86.8,  45. ,  49.3,  43.9,  17.4,  50.4,  56.5,
        64.3,  59.9,  68.1,  82.9,  55.3,  41. ,  82.8,  60.9,  21.6,
        35.2,  53. ,  79.3,  19.9,  79.1,  79.2,  48.7,  45.8,  88.4,
        87.1,  91.1,  62.1,  37.7,  24.5,  74.3,  37.8,  30. ,  84.7,
        32.9,  40.1,  70.7,  59.3,  73.7,  67.9,  69.4,  98.8,  70.6,
        87.6,  85.8,  95.3,  61.1,  48.2,  20. ,  58.5,  57.5,  41.5,
        72.5,  59.8,  52.4,  87.5,  57.1,  57.4,  74.8,  88.1,  96.2,
        79.8,  94.7,  53.4,  61.5,  67.5,  48.5,  90.9,  47.5,  85.4,
        73.3,  58.6,  65.6,  51.5,  52.9,  59.1,  82.2,  20.2,  46.5,
        62.9,  54.7,  85.9,  21.4,  63.7,  31.1,  58.7,  77.1,  64.4,
        63.4,  47.3,  85.6,  98. ,  73.1,  40.9,  71.7,  78.9,  34.3,
        42.4,  67.6,  91. ,  88.8,  63. ,  77.4,  95.2,  96.5,  78.4,
        50.3,  42.5,  80.8,  71.4,  75.6,  26.8,  57.3,  46.8,  16.6,
        56.2,  71.8,  62. ,  65. ,  39.1,  39. ,  79.4,  20.4,  87. ,
        89.1,  58.3,  18.4,  75.9,  74.5,  77.5,  58.4,  45.4,  93.8,
        49.4,  80.7,  87.7,  39.7,  56.8,  50.8,  74.1,  68.9,  41.3,
        53.6,  42.3,  72. ,  95.1,  48.1,  28.1,  75. ,  70.5,  25.3,
        69.2,  36.5,  74.2,  76.5,  67. ,  57.8,  67.8,  70.2,  88.9,
        99.2,  88.7,  58. ,  65.2,  30.7,  75.7,  68.2,  63.9,  64.2,
        56.1,  86.5,  84.8,  55.8,  92.9,  67.4,  75.4,  89.3,  91.8,
        86.1,  69.1,  65.1,  55. ,  44. ,  82.4,  76.2,  73. ,  29.8,
        31.9,  59.4,  89.5,  62.8,  49.2,  69.5,  98.5,  38.9,  97.6,
        55.4,  40.8,  84.6,  33.4,  94.3,  41.9,  82.6,  61.9,  85.5,
        87.8,  60.1,  81.8,  67.1,  81. ,  82.3,  63.6,  95.6,  70.8,
        56.4,  93.9,  64.5,  52.2,  40.4,  47.9,  31.5,  44.3,  83. ,
        35.9,  77. ,  80.4,  95.9,  76.1,  63.8,  69.8,  92.8,  93.2,
        34.6,  64.8,  90.4,  93.7,  53.9,  52.6,  76.8,  72.2,  54. ,
        45.5,  96.4,  54.9,  77.3,  93.6,  68.3,  86.7,  81.1,  72.6,
        65.3,  64.9,  74.9,  54.4,  90.8,  88. ,  76.9,  60.4,  92.4,
        82.1,  78.2,  35.7,  75.5,  75.8,  85. ,  80.1,  60.5,  62.3,
        81.5,  80.9,  77.2,  78. ,  78.1,  50.7,  93.3,  90.3,  73.5,
        86. ,  78.5])

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 81697 entries, 0 to 81696
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         81697 non-null  int64
 1   institution  81697 non-null  object
 2   rank         73256 non-null  float64
 3   score        68926 non-null  float64
 4   metric       81697 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 3.1+ MB

In [27]:
df['metric'].unique()

array(['Employer Reputation', 'International Student Ratio',
       'Academic Reputation', 'International Faculty Ratio',
       'Sustainability', 'Employment Outcomes', 'Faculty Student Ratio',
       'Citations per Faculty', 'International Research Network',
       'Overall', 'International Student Diversity'], dtype=object)

In [10]:
df.to_csv('../data/qs_data.csv', index=False)

In [12]:
df['metric'].unique()

array(['Employer Reputation', 'International Students',
       'Academic Reputation', 'International Faculty', 'Sustainability',
       'Employment Outcomes', 'Faculty Student Ratio',
       'Citations per Faculty', 'International Research Network',
       'Overall', 'International Student Diversity'], dtype=object)