In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('../data/qs_data.csv', encoding='latin1')

In [3]:
df

,year,institution,rank,score,metric
0,2023,Universidad del Valle,501.0,16.9,Employer Reputation
1,2023,Beijing Jiaotong University,601.0,11.8,International Student Ratio
2,2024,Free University of Bozen-Bolzano,601.0,5.0,Academic Reputation
3,2026,Ohio State University,131.0,71.1,Academic Reputation
4,2025,Hokkaido University,613.0,18.7,International Faculty Ratio
...,...,...,...,...,...
77370,2025,"Universita' degli Studi ""G. d'Annunzio"" Chieti...",701.0,3.3,Faculty Student Ratio
77371,2023,Western Michigan University,501.0,6.6,Employer Reputation
77372,2027,University of Toledo,801.0,15.8,Employment Outcomes
77373,2024,Canterbury Christ Church University,701.0,5.8,Faculty Student Ratio
77374,2027,Western University,24.0,95.3,Sustainability

In [6]:
# remove international student diversity - no longer included since 2027
df = df[df['metric']!='International Student Diversity']

In [7]:
df["metric"] = df["metric"].replace({
    "International Students": "International Student Ratio",
    "International Faculty": "International Faculty Ratio",
})

C:\Users\zue12aeu\AppData\Local\Temp\ipykernel_6408\4120623342.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["metric"] = df["metric"].replace({

In [8]:
df.head()

,year,institution,rank,score,metric
0,2023,Universidad del Valle,501.0,16.9,Employer Reputation
1,2023,Beijing Jiaotong University,601.0,11.8,International Student Ratio
2,2024,Free University of Bozen-Bolzano,601.0,5.0,Academic Reputation
3,2026,Ohio State University,131.0,71.1,Academic Reputation
4,2025,Hokkaido University,613.0,18.7,International Faculty Ratio

In [9]:
# Replace any dashes with blank values.
df["score"] = (
    pd.to_numeric(
        df["score"].replace("-", pd.NA),
        errors="coerce"
    )
)

C:\Users\zue12aeu\AppData\Local\Temp\ipykernel_6408\872485869.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["score"] = (

In [10]:
# now remove any overalls with a blank value
df = df[~((df["metric"] == "Overall") & (df["score"].isna()))]

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69948 entries, 0 to 77374
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   year         69948 non-null  int64
 1   institution  69948 non-null  object
 2   rank         67470 non-null  float64
 3   score        67462 non-null  float64
 4   metric       69948 non-null  object
dtypes: float64(2), int64(1), object(2)
memory usage: 3.2+ MB

In [12]:
df['metric'].unique()

array(['Employer Reputation', 'International Student Ratio',
       'Academic Reputation', 'International Faculty Ratio',
       'Sustainability', 'Employment Outcomes', 'Faculty Student Ratio',
       'Citations per Faculty', 'International Research Network',
       'Overall'], dtype=object)

In [13]:
df.to_csv('../data/qs_data.csv', index=False)

In [12]:
df['metric'].unique()

array(['Employer Reputation', 'International Students',
       'Academic Reputation', 'International Faculty', 'Sustainability',
       'Employment Outcomes', 'Faculty Student Ratio',
       'Citations per Faculty', 'International Research Network',
       'Overall', 'International Student Diversity'], dtype=object)